# Generated by Django 4.0.4 on 2022-05-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbre',
            name='localisation',
            field=models.CharField(max_length=30),
        ),
    ]
